apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditseverityservicedepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditSeverityMicroService
  template:
    metadata:
      labels:
        app: AuditSeverityMicroService
    spec:
      containers:
      - name: severityregistry
        image: auditseveritycr.azurecr.io/severityregistry:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn1

---
apiVersion: v1
kind: Service
metadata:
  name: auditseverityservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditSeverityMicroService
